# Generated by Django 3.1.3 on 2021-01-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key_word', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('clean_twits', models.CharField(max_length=1000000)),
                ('cooked', models.CharField(default='', max_length=1000000)),
                ('word_count', models.CharField(default='', max_length=1000000)),
                ('twits', models.CharField(max_length=1000000)),
                ('user_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
