# Generated by Django 3.1.3 on 2021-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='clean_twits',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='twit',
            name='cooked',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='twit',
            name='twits',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='twit',
            name='word_count',
            field=models.JSONField(),
        ),
    ]
