# Generated by Django 3.1.3 on 2021-01-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='folks',
        ),
    ]
